$(document).ready(function() {
  $("#js-desc").click(function(){
    $("#js-answer").toggle();
  });
  $("#op-desc").click(function(){
    $("#op-answer").toggle();
  });
  $("#va-desc").click(function(){
    $("#va-answer").toggle();
  });
  $("#vnc-desc").click(function(){
    $("#vnc-answer").toggle();
  });
  $("#fun-desc").click(function(){
    $("#fun-answer").toggle();
  });
  $("#met-desc").click(function(){
    $("#met-answer").toggle();
  });
  $("#arg-desc").click(function(){
    $("#arg-answer").toggle();
  });
  $("#par-desc").click(function(){
    $("#par-answer").toggle();
  });
  $("#ret-desc").click(function(){
    $("#ret-answer").toggle();
  });
  $("#cm-desc").click(function(){
    $("#cm-answer").toggle();
  });
  $("#str-desc").click(function(){
    $("#str-answer").toggle();
  });
  $("#boo-desc").click(function(){
    $("#boo-answer").toggle();
  });
  $("#und-desc").click(function(){
    $("#und-answer").toggle();
  });
  $("#nan-desc").click(function(){
    $("#nan-answer").toggle();
  });
  $("#null-desc").click(function(){
    $("#null-answer").toggle();
  });
  $("#al-desc").click(function(){
    $("#al-answer").toggle();
  });
  $("#com-desc").click(function(){
    $("#com-answer").toggle();
  });
  $("#jq-desc").click(function(){
    $("#jq-answer").toggle();
  });
  $("#att-desc").click(function(){
    $("#att-answer").toggle();
  })
});